version: '3.8'

services:
  pushvoice-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pushvoice-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WS_URL=ws://votre-domaine.com:8080
      - JWT_SECRET=votre-jwt-secret-tres-securise
    volumes:
      - ./logs:/app/logs
    networks:
      - pushvoice-network

  nginx:
    image: nginx:alpine
    container_name: pushvoice-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - pushvoice-app
    networks:
      - pushvoice-network

networks:
  pushvoice-network:
    driver: bridge